language = "rust"
version = "0.24.0"
wasm_file = "tree-sitter-rust.wasm"
extensions = [".rs"]
display_name = "Rust"

[queries]
symbol_exists = "queries/symbol_exists.scm"

[queries.boundary_references]
source = """
[
  (use_declaration)
  (type_identifier)
  (scoped_identifier)
  (call_expression)
] @reference
"""
