language = "bash"
version = "0.23.3"
wasm_file = "tree-sitter-bash.wasm"
extensions = [".sh", ".bash"]
display_name = "Bash"

[queries]
symbol_exists = "queries/symbol_exists.scm"

[queries.boundary_references]
source = """
[
  (command_name)
  (string)
] @reference
"""
