use anyhow::Result;
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

pub fn scaffold(source_dir: &Path, output_dir: &Path) -> Result<String> {
    let supported = &["ts", "tsx", "go", "py", "rs", "cs", "prisma"];
    let mut groups: BTreeMap<String, Vec<PathBuf>> = BTreeMap::new();

    walk_source_files(source_dir, supported, &mut groups, source_dir, 0);

    if groups.is_empty() {
        anyhow::bail!(
            "no supported source files found in '{}'",
            source_dir.display()
        );
    }

    let mut out = String::new();
    out.push_str("// Generated by kide init\n");
    out.push_str("// Review and edit this file to match your domain model\n\n");

    for (group_name, files) in &groups {
        let context_name = to_pascal_case(group_name);
        out.push_str(&format!("context {}Context {{\n", context_name));

        // Generate aggregate stubs from each file
        for file in files {
            let rel = file.strip_prefix(output_dir).unwrap_or(file);
            let rel_str = rel.display().to_string();
            let stem = file
                .file_stem()
                .and_then(|s| s.to_str())
                .unwrap_or("Unknown");
            let agg_name = to_pascal_case(stem);

            out.push_str(&format!(
                "  aggregate {} bound to \"{}\" {{\n",
                agg_name,
                rel_str.replace('\\', "/")
            ));
            out.push_str("    // TODO: add fields, commands, and invariants\n");
            out.push_str("  }\n");
        }

        out.push_str("}\n\n");
    }

    Ok(out)
}

fn walk_source_files(
    dir: &Path,
    supported: &[&str],
    groups: &mut BTreeMap<String, Vec<PathBuf>>,
    root: &Path,
    depth: usize,
) {
    if depth > 10 {
        return;
    }
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
            if name.starts_with('.')
                || name == "node_modules"
                || name == "target"
                || name == "__pycache__"
            {
                continue;
            }
            walk_source_files(&path, supported, groups, root, depth + 1);
        } else if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
            if supported.contains(&ext) {
                // Group by the immediate parent directory relative to root
                let group = path
                    .parent()
                    .and_then(|p| p.strip_prefix(root).ok())
                    .map(|p| {
                        p.components()
                            .last()
                            .map(|c| c.as_os_str().to_string_lossy().to_string())
                            .unwrap_or_else(|| "root".to_string())
                    })
                    .unwrap_or_else(|| "root".to_string());
                groups.entry(group).or_default().push(path);
            }
        }
    }
}

fn to_pascal_case(s: &str) -> String {
    s.split(|c: char| c == '_' || c == '-' || c == '.')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(c) => {
                    let upper: String = c.to_uppercase().collect();
                    format!("{}{}", upper, chars.as_str())
                }
                None => String::new(),
            }
        })
        .collect()
}
