[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[alias]
build-cli-wasm = "build --release --target wasm32-wasip1 -p kide-cli"
build-runtime-wasm = "build --release --target wasm32-wasip1 -p kide"
