language = "typescript"
version = "0.23.2"
wasm_file = "tree-sitter-typescript.wasm"
tsx_wasm_file = "tree-sitter-tsx.wasm"
extensions = [".ts", ".tsx"]
display_name = "TypeScript"

[queries]
symbol_exists = "queries/symbol_exists.scm"

[queries.boundary_references]
source = """
[
  (import_statement)
  (type_identifier)
  (call_expression)
  (new_expression)
] @reference
"""
