language = "prisma"
version = "1.6.0"
wasm_file = "tree-sitter-prisma.wasm"
extensions = [".prisma"]
display_name = "Prisma"

[queries]
symbol_exists = "queries/symbol_exists.scm"

[queries.boundary_references]
source = """
[
  (column_type)
  (identifier)
] @reference
"""
